### PR TITLE
Fix unicode crap bc it breaks my shitty android ssh client

### PR DESCRIPTION
**Pull request by marcuswanner**

### CODE REVIEW

**Comment by MuffinMedic** [comment]
Is there a specific issue it's causing? I've never heard of this bug before.

**Comment by marcuswanner** [comment]
I mean this bot is in my channel (#vtluug on oftc) and it's screwing up my display. I guess we can just run our own ASCII-formatted fork?

**Comment by marcuswanner** [comment]
Like seriously though who runs the instance of TechSupport that lives in #vtluug? Is that you?

**Comment by MuffinMedic** [comment]
Yes. This is a client bug, not a bot bug. I suggest submitting an issue to your client developer to get this resolved.

**Comment by marcuswanner** [comment]
Do you run the instance of CloudBot "TechSupport" that lives in #vtluug?

**Comment by MuffinMedic** [comment]
Yes, that's my bot. I put it in there some time ago at the request of another op.

**Comment by marcuswanner** [comment]
Ok, thank you! We're gonna run our own instance from here on. Appreciate your development effort!

**Pull request closed without merging**
